### ISSUE TITLE
Support for "normal" not continous rotation Servo-Servo antenna trackers

### ISSUE THREAD

**Issue by marksev1** [raul-ortega/amv-open360tracker#2]
Hello could you maybe please add also support for  antenna tracker designs based on non-continous rotation servos. 

For example a Normal 360 degree servo + normal 180 degree servo for tilt...Or even normal 180 degree servo for pan and 180 degree servo for tilt.

This would make the base of antenna tracker hardware designs on which your code could run bigger (http://www.thingiverse.com/thing:421592). For example I have a Ghettostation antenna tracker build with two normal 180 degree servos (https://www.youtube.com/results?search_query=ghettostation).

Your code has nice improvements like magnetometer support and "mobile" groundstation support vs a regular Ghettostation.

**Comment by raul-ortega** [comment]
The source code is written to provide support for full 360° continuous rotation in PAN servo, and it is used with TILT servo of 180º, moving it from 0 to 90º. This is one of the most important advantages of using this firmware. It has no sense, at less for us (our FPV community) go back to 180 or use it with not continuous rotation 360º servos. We want the antenna pointing to the target all the time, thats the reason why we moved to this system.

I apologize, but I'm not agree to give support for this issue, it's easier to modify the pan servo...

**Comment by marksev1** [comment]
Fair enough :). Can you then just please point me to relevant lines of code which I could try and change for myself? After that I will close the issue :)
